[package]
name = "pipeviewer"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { workspace = true, features = ["derive", "env"] }
crossbeam = { workspace = true }
crossterm = { workspace = true }

[lints]
workspace = true
