[package]
name = "axum-webservice"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true, features = ["full"] }
axum = { workspace = true }

[lints]
workspace = true

[dev-dependencies]
anyhow = { workspace = true }
